# Generated by Django 4.2.1 on 2023-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="Unique hex encoded identifier for each reward grant event generated by AdMob.",
                        max_length=256,
                    ),
                ),
                (
                    "timestamp",
                    models.PositiveBigIntegerField(
                        help_text="Timestamp of when the user was rewarded as Epoch time in ms."
                    ),
                ),
                (
                    "ad_network",
                    models.PositiveBigIntegerField(
                        help_text="Ad network identifier for the network that fulfilled this ad."
                    ),
                ),
                (
                    "ad_unit",
                    models.PositiveBigIntegerField(
                        help_text="AdMob ad unit id that was used to request the rewarded video ad."
                    ),
                ),
                (
                    "reward_amount",
                    models.PositiveIntegerField(
                        help_text="Reward amount as specified in the ad unit settings."
                    ),
                ),
                (
                    "reward_item",
                    models.CharField(
                        help_text="Reward item as specified in the ad unit settings.",
                        max_length=512,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True,
                        help_text="User identifier as provided by your app.",
                        max_length=256,
                    ),
                ),
                (
                    "custom_data",
                    models.CharField(
                        blank=True,
                        help_text="Custom data string as provided by your app.",
                        max_length=1024,
                    ),
                ),
                (
                    "key_id",
                    models.PositiveBigIntegerField(
                        help_text="Key to be used to verify SSV callback."
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        help_text="Signature for SSV callback generated by AdMob.",
                        max_length=512,
                    ),
                ),
            ],
        ),
    ]
