# Generated by Django 4.2.4 on 2023-09-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verification",
            name="custom_data",
            field=models.CharField(
                blank=True,
                help_text="Custom data string as provided by your app.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="user_id",
            field=models.CharField(
                blank=True,
                help_text="User identifier as provided by your app.",
                max_length=256,
                null=True,
            ),
        ),
    ]
